-- 0001_initial_schema.sql
-- 기초 회원 및 가구(Household) 체계, 마스터 데이터 생성

CREATE TABLE IF NOT EXISTS households (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS household_members (
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    role text CHECK (role IN ('owner','member')),
    PRIMARY KEY (household_id, user_id)
);

CREATE TABLE IF NOT EXISTS account_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    sort_order int DEFAULT 0,
    is_active bool DEFAULT true
);

CREATE TABLE IF NOT EXISTS accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    group_id bigint REFERENCES account_groups(id) ON DELETE SET NULL,
    name text NOT NULL,
    account_type text CHECK (account_type IN ('bank','brokerage','virtual','external')),
    currency text DEFAULT 'KRW',
    opening_balance numeric(18,2) DEFAULT 0,
    is_active bool DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    parent_id bigint REFERENCES categories(id) ON DELETE CASCADE,
    name text NOT NULL,
    sort_order int DEFAULT 0,
    is_active bool DEFAULT true
);

CREATE TABLE IF NOT EXISTS tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    is_active bool DEFAULT true,
    UNIQUE(household_id, name)
);

-- Profiles
CREATE TABLE IF NOT EXISTS profiles (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name text,
    created_at timestamptz DEFAULT now()
);

-- Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id bigserial PRIMARY KEY,
    household_id uuid,
    user_id uuid,
    action text,
    payload_json jsonb,
    created_at timestamptz DEFAULT now()
);

-- RLS Enable
ALTER TABLE households ENABLE ROW LEVEL SECURITY;
ALTER TABLE household_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
