-- 0002_transaction_schema.sql
-- 거래 내역(복식부기 전표), 예산, 자동이체, 월 마감 테이블

CREATE TABLE IF NOT EXISTS transaction_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    occurred_at timestamptz NOT NULL,
    entry_type text CHECK (entry_type IN ('income','expense','transfer','adjustment')),
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    memo text,
    source text CHECK (source IN ('manual','import','auto_transfer','loan','system')),
    is_locked bool DEFAULT false,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transaction_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id bigint REFERENCES transaction_entries(id) ON DELETE CASCADE,
    account_id bigint REFERENCES accounts(id) ON DELETE RESTRICT,
    amount numeric(18,2) NOT NULL,
    line_memo text
);

CREATE TABLE IF NOT EXISTS entry_tags (
    entry_id bigint REFERENCES transaction_entries(id) ON DELETE CASCADE,
    tag_id bigint REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (entry_id, tag_id)
);

CREATE TABLE IF NOT EXISTS auto_transfer_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    from_account_id bigint REFERENCES accounts(id) ON DELETE CASCADE,
    to_account_id bigint REFERENCES accounts(id) ON DELETE CASCADE,
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    amount_expected numeric(18,2),
    schedule_type text CHECK (schedule_type IN ('monthly','weekly','oneoff')),
    day_of_month int,
    tolerance_days int DEFAULT 2,
    tolerance_amount numeric(18,2) DEFAULT 0,
    start_date date,
    end_date date,
    is_active bool DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auto_transfer_instances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    rule_id bigint REFERENCES auto_transfer_rules(id) ON DELETE CASCADE,
    due_date date,
    expected_amount numeric(18,2),
    status text CHECK (status IN ('pending','confirmed','missed','skipped')),
    confirmed_at timestamptz,
    confirmed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    generated_entry_id bigint REFERENCES transaction_entries(id) ON DELETE SET NULL,
    note text
);

CREATE TABLE IF NOT EXISTS budget_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    is_default bool DEFAULT false
);

CREATE TABLE IF NOT EXISTS budget_template_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id bigint REFERENCES budget_templates(id) ON DELETE CASCADE,
    category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
    monthly_amount numeric(18,2)
);

CREATE TABLE IF NOT EXISTS budget_month_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    year_month char(7),
    category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
    amount numeric(18,2),
    UNIQUE(household_id, year_month, category_id)
);

CREATE TABLE IF NOT EXISTS month_closings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    year_month char(7) NOT NULL,
    closed_at timestamptz,
    closed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    summary_json jsonb,
    UNIQUE(household_id, year_month)
);

-- Import Profiles & Rules
CREATE TABLE IF NOT EXISTS import_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text,
    mapping_json jsonb
);

CREATE TABLE IF NOT EXISTS classification_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    pattern text,
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    tag_ids jsonb,
    priority int DEFAULT 100,
    is_active bool DEFAULT true
);

-- RLS Enable
ALTER TABLE transaction_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_transfer_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_transfer_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE month_closings ENABLE ROW LEVEL SECURITY;
