-- 0003_phase2_loans_investments.sql
-- 대출 및 투자 관리를 위한 Phase 2 확장 테이블

-- [Loans]
CREATE TABLE IF NOT EXISTS loans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    principal_original numeric(18,2),
    start_date date,
    maturity_date date,
    term_months int,
    repayment_type text CHECK (repayment_type IN ('interest_only','annuity','equal_principal','custom_schedule')),
    interest_pay_day int,
    day_count_convention text DEFAULT 'ACT365',
    rounding_rule text DEFAULT 'round' CHECK (rounding_rule IN ('round','floor','ceil')),
    linked_payment_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
    is_active bool DEFAULT true,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS loan_rate_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id bigint REFERENCES loans(id) ON DELETE CASCADE,
    effective_date date NOT NULL,
    annual_rate numeric(8,6) NOT NULL,
    UNIQUE(loan_id, effective_date)
);

CREATE TABLE IF NOT EXISTS loan_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id bigint REFERENCES loans(id) ON DELETE CASCADE,
    period_start date,
    period_end date,
    posting_date date,
    interest_amount numeric(18,2),
    principal_amount numeric(18,2),
    fee_amount numeric(18,2) DEFAULT 0,
    balance_after numeric(18,2),
    locked bool DEFAULT true,
    generated_entry_id bigint REFERENCES transaction_entries(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS loan_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id bigint REFERENCES loans(id) ON DELETE CASCADE,
    event_date date NOT NULL,
    event_type text CHECK (event_type IN ('prepayment','rate_change','manual_adjust')),
    amount numeric(18,2),
    fee_amount numeric(18,2),
    note text
);

-- [Investments]
CREATE TABLE IF NOT EXISTS securities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    ticker text NOT NULL,
    name text,
    currency text DEFAULT 'KRW',
    market text,
    UNIQUE(household_id, ticker)
);

CREATE TABLE IF NOT EXISTS holdings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    security_id bigint REFERENCES securities(id) ON DELETE CASCADE,
    account_id bigint REFERENCES accounts(id) ON DELETE CASCADE,
    quantity numeric(18,6) NOT NULL,
    avg_price numeric(18,6) NOT NULL,
    last_price numeric(18,6),
    last_price_updated_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS holding_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    snapshot_date date NOT NULL,
    security_id bigint REFERENCES securities(id) ON DELETE CASCADE,
    account_id bigint REFERENCES accounts(id) ON DELETE CASCADE,
    quantity numeric(18,6),
    avg_price numeric(18,6),
    last_price numeric(18,6),
    estimated_value numeric(18,2),
    UNIQUE(household_id, snapshot_date, security_id, account_id)
);

-- RLS Enable
ALTER TABLE loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_rate_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE securities ENABLE ROW LEVEL SECURITY;
ALTER TABLE holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE holding_snapshots ENABLE ROW LEVEL SECURITY;
