-- =============================================================
-- Sprint 1: 기반 보강 마이그레이션
-- [CRITICAL] is_locked RLS + account_groups + notifications + audit_logs + Views
-- =============================================================

-- =============================================
-- 1. [CRITICAL] is_locked 전표 보호 정책
-- 마감(is_locked=true)된 전표는 UPDATE/DELETE 불가
-- 조정 전표(adjustment)로만 수정 반영
-- =============================================

-- 기존 RLS 정책 제거 후 재생성 (충돌 방지)
DROP POLICY IF EXISTS "Members can manage transaction_entries" ON transaction_entries;
DROP POLICY IF EXISTS "Members can select transaction_entries" ON transaction_entries;
DROP POLICY IF EXISTS "Members can insert transaction_entries" ON transaction_entries;
DROP POLICY IF EXISTS "Members can update transaction_entries" ON transaction_entries;
DROP POLICY IF EXISTS "Members can delete transaction_entries" ON transaction_entries;

-- SELECT: 가구 멤버는 조회 가능
CREATE POLICY "Members can select transaction_entries"
    ON transaction_entries FOR SELECT TO authenticated
    USING (is_household_member(household_id));

-- INSERT: 가구 멤버는 삽입 가능
CREATE POLICY "Members can insert transaction_entries"
    ON transaction_entries FOR INSERT TO authenticated
    WITH CHECK (is_household_member(household_id));

-- UPDATE: 가구 멤버 + is_locked=false인 전표만 수정 가능
CREATE POLICY "Members can update unlocked transaction_entries"
    ON transaction_entries FOR UPDATE TO authenticated
    USING (is_household_member(household_id) AND is_locked = false)
    WITH CHECK (is_household_member(household_id));

-- DELETE: 가구 멤버 + is_locked=false인 전표만 삭제 가능
CREATE POLICY "Members can delete unlocked transaction_entries"
    ON transaction_entries FOR DELETE TO authenticated
    USING (is_household_member(household_id) AND is_locked = false);

-- =============================================
-- 2. account_groups 테이블 (Schema 3.1)
-- 계좌를 그룹으로 묶어 대시보드/리포트에서 활용
-- Phase 2 투자 계좌(brokerage) 분류의 기반
-- =============================================

CREATE TABLE IF NOT EXISTS account_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    sort_order int DEFAULT 0,
    is_active bool DEFAULT true,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE account_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can manage account_groups"
    ON account_groups FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));

-- accounts 테이블에 group_id FK 추가 (기존 계좌에는 NULL 허용)
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES account_groups(id) ON DELETE SET NULL;

-- =============================================
-- 3. notifications 테이블 (Schema 7.3)
-- 자동이체 미확인 알림, 마감 리마인드 등
-- =============================================

CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    type text NOT NULL,           -- 'auto_transfer_missed', 'closing_reminder', 'budget_exceeded' 등
    payload_json jsonb,           -- 추가 데이터 (규칙명, 금액 등)
    created_at timestamptz DEFAULT now(),
    read_at timestamptz           -- NULL이면 미읽음
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 본인 알림만 조회/관리 가능
CREATE POLICY "Users can manage own notifications"
    ON notifications FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- 인덱스: 미읽음 알림 빠른 조회
CREATE INDEX IF NOT EXISTS idx_notifications_unread
    ON notifications(user_id, created_at DESC)
    WHERE read_at IS NULL;

-- =============================================
-- 4. audit_logs 테이블 (Schema 2.4)
-- 중요 이벤트(마감, 대출 생성 등) 기록
-- =============================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    action text NOT NULL,         -- 'close_month', 'create_loan', 'delete_account' 등
    payload_json jsonb,           -- 상세 내용
    created_at timestamptz DEFAULT now()
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 가구 멤버는 조회만 가능 (INSERT는 RPC/서버에서만)
CREATE POLICY "Members can view audit_logs"
    ON audit_logs FOR SELECT TO authenticated
    USING (is_household_member(household_id));

-- INSERT는 서비스 역할(SECURITY DEFINER RPC)에서만 수행하므로
-- 일반 사용자의 직접 INSERT를 허용하되, 변조 방지는 별도 관리
CREATE POLICY "Members can insert audit_logs"
    ON audit_logs FOR INSERT TO authenticated
    WITH CHECK (is_household_member(household_id));

-- =============================================
-- 5. 권장 View (Schema 13)
-- 집계 쿼리를 View로 제공하여 프론트 훅에서 쉽게 활용
-- =============================================

-- 5-1. 계좌별 실제 잔액 (opening_balance + 거래 합산)
CREATE OR REPLACE VIEW v_account_balance_actual AS
SELECT
    a.id AS account_id,
    a.household_id,
    a.name AS account_name,
    a.account_type,
    a.opening_balance,
    COALESCE(SUM(tl.amount), 0) AS transaction_total,
    a.opening_balance + COALESCE(SUM(tl.amount), 0) AS current_balance
FROM accounts a
LEFT JOIN transaction_lines tl ON tl.account_id = a.id
LEFT JOIN transaction_entries te ON te.id = tl.entry_id
WHERE a.is_active = true
GROUP BY a.id, a.household_id, a.name, a.account_type, a.opening_balance;

-- 5-2. 월별 카테고리별 실적 집계
CREATE OR REPLACE VIEW v_monthly_category_actual AS
SELECT
    te.household_id,
    TO_CHAR(te.occurred_at, 'YYYY-MM') AS year_month,
    te.entry_type,
    te.category_id,
    c.name AS category_name,
    c.parent_id AS category_parent_id,
    COALESCE(SUM(CASE WHEN tl.amount > 0 THEN tl.amount ELSE 0 END), 0) AS total_inflow,
    COALESCE(SUM(CASE WHEN tl.amount < 0 THEN ABS(tl.amount) ELSE 0 END), 0) AS total_outflow,
    COUNT(DISTINCT te.id) AS entry_count
FROM transaction_entries te
JOIN transaction_lines tl ON tl.entry_id = te.id
LEFT JOIN categories c ON c.id = te.category_id
GROUP BY te.household_id, TO_CHAR(te.occurred_at, 'YYYY-MM'), te.entry_type, te.category_id, c.name, c.parent_id;

-- =============================================
-- 6. 권장 인덱스 (Schema 4 권장)
-- =============================================

CREATE INDEX IF NOT EXISTS idx_te_household_occurred
    ON transaction_entries(household_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_te_household_category_occurred
    ON transaction_entries(household_id, category_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_tl_account
    ON transaction_lines(account_id);

CREATE INDEX IF NOT EXISTS idx_entry_tags_tag
    ON entry_tags(tag_id);
