-- =============================================================
-- Sprint 3: favorite_templates 테이블 (즐겨찾기 거래 템플릿)
-- 사용자 요청에 따라 DB 테이블로 구현 (멀티 디바이스 동기화)
-- =============================================================

CREATE TABLE IF NOT EXISTS favorite_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    name text NOT NULL,
    entry_type text CHECK (entry_type IN ('income','expense','transfer')),
    from_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
    to_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    amount numeric(18,2),
    memo text,
    sort_order int DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE favorite_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can manage favorite_templates"
    ON favorite_templates FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
