-- 0023_investment_targets.sql
-- 사용자별 목표 포트폴리오(PF) 비중 설정 관리

CREATE TABLE IF NOT EXISTS investment_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID REFERENCES households(id) ON DELETE CASCADE,
    theme TEXT NOT NULL,           -- 'index', 'dividend', 'bond', 'gold', 'china', 'theme', 'individual', 'cash' 등
    target_weight NUMERIC(5,2),    -- 목표 비중 (%) 예: 30.00
    label TEXT,                    -- 화면에 표시할 한글 라벨 (예: '지수+채권')
    currency_type TEXT DEFAULT 'all', -- 원화/외화 구분용 ('krw', 'usd', 'all')
    sort_order INT DEFAULT 0,
    UNIQUE(household_id, theme, currency_type)
);

ALTER TABLE investment_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can manage investment_targets" ON investment_targets;
CREATE POLICY "Members can manage investment_targets"
    ON investment_targets FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
