-- 0024_monthly_asset_snapshots.sql
-- 월 단위 자산 현황 스냅샷 기록(대시보드 히스토리용)

CREATE TABLE IF NOT EXISTS monthly_asset_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID REFERENCES households(id) ON DELETE CASCADE,
    year_month CHAR(7) NOT NULL,   -- 'YYYY-MM' 포맷 (예: '2026-02')
    snapshot_json JSONB NOT NULL,  -- 투자, 예금, 부동산, 부채, 합계 등 모든 자산 데이터를 담는 JSON
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(household_id, year_month)
);

ALTER TABLE monthly_asset_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can manage monthly_asset_snapshots" ON monthly_asset_snapshots;
CREATE POLICY "Members can manage monthly_asset_snapshots"
    ON monthly_asset_snapshots FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
