-- 0025_monthly_contributions.sql
-- 매월 정기적으로 투자할 자본금의 배분계획을 수립하는 테이블

CREATE TABLE IF NOT EXISTS monthly_investment_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID REFERENCES households(id) ON DELETE CASCADE,
    theme TEXT NOT NULL,            -- 투자 테마명
    currency_type TEXT NOT NULL,    -- 통화 구분 ('krw', 'usd')
    target_weight NUMERIC(5,2),     -- 배분 목표 비중 (%)
    target_amount NUMERIC(18,2),    -- 실제 배분 목표 금액
    target_account TEXT,            -- 투자금을 입금할 계좌(별칭)
    sort_order INT DEFAULT 0,
    UNIQUE(household_id, theme, currency_type)
);

ALTER TABLE monthly_investment_contributions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can manage monthly_investment_contributions" ON monthly_investment_contributions;
CREATE POLICY "Members can manage monthly_investment_contributions"
    ON monthly_investment_contributions FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
