-- 0026_pet_care_logs.sql
-- 반려견 유치원(무무누리 등) 이용 내역을 기록하는 독립된 소비 로그

CREATE TABLE IF NOT EXISTS pet_care_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID REFERENCES households(id) ON DELETE CASCADE,
    visit_number INT,                  -- 이용 회차 (1, 2, 3...)
    check_in_date DATE NOT NULL,       -- 입실일
    check_in_time TIME,                -- 입실시간
    check_out_date DATE,               -- 퇴실일
    check_out_time TIME,               -- 퇴실시간
    stay_days INT,                     -- 이용일 수
    extra_hours_before9 NUMERIC(4,1) DEFAULT 0,  -- 초과시간(9시 이전 입실)
    extra_hours_after18 NUMERIC(4,1) DEFAULT 0,  -- 초과시간(18시 이후 퇴실)
    base_fee NUMERIC(18,2) DEFAULT 0,  -- 기본요금
    nuri_fee NUMERIC(18,2) DEFAULT 0,  -- 누리 기본요금 (20kg이상)
    extra_fee_morning NUMERIC(18,2) DEFAULT 0,  -- 초과요금(09시 이전)
    extra_fee_evening NUMERIC(18,2) DEFAULT 0,  -- 초과요금(18시 이후)
    total_fee NUMERIC(18,2) DEFAULT 0, -- 총 요금 (합산)
    memo TEXT,                         -- 비고
    linked_entry_id BIGINT REFERENCES transaction_entries(id) ON DELETE SET NULL,  -- 실제 돈이 나간 일반 수입/지출 전표 연결
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE pet_care_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can manage pet_care_logs" ON pet_care_logs;
CREATE POLICY "Members can manage pet_care_logs"
    ON pet_care_logs FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
