-- =============================================================
-- 0034: 개인 용돈 관리 테이블 (덕원/여선)
-- [PM] PRD 원칙: "개인 용돈은 지급액만 기록, 사용내역 미기록"
-- 월 예산 + 고정지출 관리 + 잔액 추적
-- =============================================================

-- 1. 구성원별 월 용돈 예산 테이블
CREATE TABLE IF NOT EXISTS personal_allowances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    member_name text NOT NULL,                    -- '덕원' 또는 '여선'
    year_month char(7) NOT NULL,                  -- '2026-03'
    budget_amount numeric(18,2) NOT NULL DEFAULT 0, -- 이번 달 용돈 총액
    memo text,                                     -- 비고
    created_by uuid REFERENCES profiles(user_id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now(),
    UNIQUE(household_id, member_name, year_month)  -- 구성원+월 단위 유니크
);

-- 2. 개인 고정지출 항목 테이블
CREATE TABLE IF NOT EXISTS allowance_fixed_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    member_name text NOT NULL,                    -- '덕원' 또는 '여선'
    label text NOT NULL,                          -- '유튜브 프리미엄', '국민건강보험' 등
    amount numeric(18,2) NOT NULL DEFAULT 0,      -- 고정 금액
    category text DEFAULT '기타',                  -- '구독', '보험', '통신', '기타'
    is_active bool DEFAULT true,                   -- 활성 여부
    sort_order int DEFAULT 0,                      -- 정렬 순서
    created_by uuid REFERENCES profiles(user_id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now()
);

-- 3. RLS 활성화
ALTER TABLE personal_allowances ENABLE ROW LEVEL SECURITY;
ALTER TABLE allowance_fixed_expenses ENABLE ROW LEVEL SECURITY;

-- 4. RLS 정책
DROP POLICY IF EXISTS "Members can manage personal_allowances" ON personal_allowances;
CREATE POLICY "Members can manage personal_allowances"
    ON personal_allowances FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));

DROP POLICY IF EXISTS "Members can manage allowance_fixed_expenses" ON allowance_fixed_expenses;
CREATE POLICY "Members can manage allowance_fixed_expenses"
    ON allowance_fixed_expenses FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));
