-- 0039_budget_term_override.sql
-- 단일 월 예산 오버라이드를 기간(start_month ~ end_month) 기반 오버라이드로 변경

-- 1. 새로운 기간 오버라이드 테이블 생성
CREATE TABLE IF NOT EXISTS budget_term_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id uuid REFERENCES households(id) ON DELETE CASCADE,
    category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
    start_year_month char(7) NOT NULL, -- YYYY-MM
    end_year_month char(7) NOT NULL,   -- YYYY-MM
    amount numeric(18,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    -- 시작월이 종료월보다 작거나 같아야 함
    CONSTRAINT budget_term_overrides_period_check CHECK (start_year_month <= end_year_month)
);

-- RLS 활성화 및 정책 추가
ALTER TABLE budget_term_overrides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can manage budget_term_overrides" ON budget_term_overrides;
CREATE POLICY "Members can manage budget_term_overrides"
    ON budget_term_overrides FOR ALL TO authenticated
    USING (is_household_member(household_id))
    WITH CHECK (is_household_member(household_id));

-- 2. 기존 budget_month_overrides 데이터를 새 테이블로 이관
INSERT INTO budget_term_overrides (household_id, category_id, start_year_month, end_year_month, amount)
SELECT household_id, category_id, year_month, year_month, amount
FROM budget_month_overrides;

-- 3. 기존 budget_month_overrides 테이블 삭제 (또는 남겨두되 향후 사용 안함)
-- 여기서 바로 DROP 하지 않고 안전을 위해 구조만 남겨두거나 삭제할 수 있음.
-- 임시로 삭제 처리
DROP TABLE IF EXISTS budget_month_overrides;
